### PR TITLE
Remove kr server

### PR DESCRIPTION
**Pull request by Kieaer**
No players 5 months (There were several attempts to connect, but couldn't join because classic version didn't update the client)
Anuke you're last player lol

### CODE REVIEW

**Comment by RebornTrack970** [comment]
hm

**Comment by Wetelemon** [comment]
pretty old request, probably ignored by the cat

**Comment by Kieaer** [comment]
@Wetelemon Anuke doesn't update classic version lol

**Comment by Wetelemon** [comment]
oh it's about classic
kek I didn't read

**Comment by Anuken** [comment]
No longer updating this, as I don't have the right setup to deploy builds at all.

**Pull request closed without merging**
